apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealplan-deployment
  labels:
    app: mealplan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealplan
  template:
    metadata:
      labels:
        app: mealplan
    spec:
      containers:
      - name: mealplan
        image: deeaxfun2/meal_plan:latest
        ports:
        - containerPort: 8003
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: AUTH_SERVICE_HOST_URL
          value: "http://192.168.194.36/api/v1"
        - name: RECIPE_SERVICE_HOST_URL
          value: "http://192.168.194.28/api/v1"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: jwt-secret
        - name: ALGORITHM
          value: "HS256"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30" 
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: MYSQL_HOST
          value: "192.168.194.14"  # MySQL service name
        - name: MYSQL_PORT
          value: "3306"        # MySQL default port
        - name: MYSQL_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
